import { NextRequest } from 'next/server'
import { verifyAgentKey, unauthorized, success } from '@/lib/agent-auth'

export const dynamic = 'force-dynamic'

export async function GET(request: NextRequest) {
  if (!verifyAgentKey(request)) return unauthorized()

  return success({
    name: 'bagas.dev Agent API',
    version: '1.0.0',
    description: 'API for AI agents to read and write data on bagas.dev',
    auth: 'Bearer token via Authorization header (AGENT_API_KEY)',
    responseFormat: '{ ok: boolean, data?: any, error?: string }',
    endpoints: [
      {
        method: 'GET',
        path: '/api/agent',
        description: 'This discovery endpoint — returns full API contract',
      },
      {
        method: 'GET',
        path: '/api/agent/overview',
        description: 'Site summary: content counts, site settings, recent posts/projects',
      },
      {
        method: 'GET',
        path: '/api/agent/posts',
        description: 'List posts/notes',
        params: {
          type: 'string — "post" | "note" | "post,note" (default: "post,note")',
          published: 'string — "true" | "false" | "all" (default: "all")',
          limit: 'number (default: 50)',
          offset: 'number (default: 0)',
          search: 'string — search title/content',
        },
        response: '{ posts: Post[], total: number }',
      },
      {
        method: 'GET',
        path: '/api/agent/posts/:slug',
        description: 'Get single post by slug (full content)',
        response: 'Post',
      },
      {
        method: 'POST',
        path: '/api/agent/posts',
        description: 'Create a new post or note',
        body: {
          title: 'string (required)',
          slug: 'string (required, unique)',
          content: 'string (required, markdown)',
          description: 'string (optional)',
          icon: 'string (optional, emoji)',
          tags: 'string[] (optional)',
          category: 'string (default: "technical")',
          type: '"post" | "note" (default: "post")',
          published: 'boolean (default: false)',
          featured: 'boolean (default: false)',
        },
        response: 'Post',
      },
      {
        method: 'PUT',
        path: '/api/agent/posts/:slug',
        description: 'Update an existing post by slug (partial update)',
        body: 'Partial<Post> — only include fields to update',
        response: 'Post',
      },
      {
        method: 'GET',
        path: '/api/agent/projects',
        description: 'List all projects',
        params: {
          featured: 'string — "true" | "false" | "all" (default: "all")',
          limit: 'number (default: 50)',
        },
        response: '{ projects: Project[], total: number }',
      },
      {
        method: 'GET',
        path: '/api/agent/projects/:slug',
        description: 'Get single project by slug',
        response: 'Project',
      },
      {
        method: 'POST',
        path: '/api/agent/projects',
        description: 'Create a new project',
        body: {
          name: 'string (required)',
          slug: 'string (required, unique)',
          description: 'string (required)',
          image: 'string (optional, URL)',
          demoUrl: 'string (optional)',
          repo: 'string (optional, GitHub URL)',
          tech: 'string[] (optional)',
          year: 'number (optional)',
          featured: 'boolean (default: false)',
          sortOrder: 'number (default: 0)',
        },
        response: 'Project',
      },
      {
        method: 'PUT',
        path: '/api/agent/projects/:slug',
        description: 'Update an existing project by slug (partial update)',
        body: 'Partial<Project> — only include fields to update',
        response: 'Project',
      },
      {
        method: 'GET',
        path: '/api/agent/skills',
        description: 'List all skills',
        params: {
          category: 'string — filter by category (optional)',
        },
        response: '{ skills: Skill[], total: number }',
      },
      {
        method: 'GET',
        path: '/api/agent/analytics',
        description: 'Traffic analytics from own PageView tracking',
        params: {
          days: 'number (default: 30)',
        },
        response: '{ summary, daily, countries, topPages, devices }',
      },
      {
        method: 'GET',
        path: '/api/agent/analytics/seo',
        description: 'Google Search Console data (if configured)',
        params: {
          days: 'number (default: 28)',
        },
        response: '{ configured, summary?, queries?, pages?, daily? }',
      },
      {
        method: 'GET',
        path: '/api/agent/site',
        description: 'Get current site settings',
        response: 'SiteSettings',
      },
      {
        method: 'PUT',
        path: '/api/agent/site',
        description: 'Update site settings (partial update)',
        body: 'Partial<SiteSettings> — only include fields to update',
        response: 'SiteSettings',
      },
    ],
    models: {
      Post: {
        id: 'string',
        title: 'string',
        slug: 'string (unique)',
        content: 'string (markdown)',
        description: 'string | null',
        icon: 'string | null',
        tags: 'string[]',
        category: 'string',
        type: '"post" | "note"',
        published: 'boolean',
        featured: 'boolean',
        createdAt: 'ISO datetime',
        updatedAt: 'ISO datetime',
      },
      Project: {
        id: 'string',
        name: 'string',
        slug: 'string (unique)',
        description: 'string',
        image: 'string | null',
        demoUrl: 'string | null',
        repo: 'string | null',
        articleUrl: 'string | null',
        githubStars: 'number | null',
        githubForks: 'number | null',
        githubLanguage: 'string | null',
        tech: 'string[]',
        year: 'number | null',
        featured: 'boolean',
        sortOrder: 'number',
        createdAt: 'ISO datetime',
        updatedAt: 'ISO datetime',
      },
      Skill: {
        id: 'string',
        name: 'string',
        slug: 'string (unique)',
        icon: 'string | null',
        url: 'string | null',
        category: 'string',
        level: 'string',
        yearsOfExp: 'number | null',
        sortOrder: 'number',
        featured: 'boolean',
      },
      SiteSettings: {
        name: 'string',
        siteName: 'string',
        tagline: 'string',
        heroIntro: 'string',
        heroImage: 'string | null',
        cvUrl: 'string',
        bio: 'string (markdown)',
        sidebarBio: 'string',
        github: 'string',
        linkedin: 'string',
        twitter: 'string',
        email: 'string',
        bluesky: 'string',
        rssEnabled: 'boolean',
      },
    },
  })
}
